package catalog

import (
	"context"
	"net/http"
	"os"
	"testing"
	"time"
)

// networkTestsEnv gates the tests that reach the real internet.
const networkTestsEnv = "YARM_NETWORK_TESTS"

func requireNetwork(t *testing.T) {
	t.Helper()
	if os.Getenv(networkTestsEnv) != "1" {
		t.Skipf("set %s=1 to run tests that reach the internet", networkTestsEnv)
	}
}

// TestRenoDXMetadataLive checks that RenoDX still publishes the file this
// package parses, at the tag it parses it from, in a shape this parser
// understands.
//
// The whole RenoDX step rests on a JSON file generated by a script in
// someone else's repository, on a rolling prerelease tag. Nothing
// guarantees either stays put, and a fixture cannot notice when they
// move. This is what notices.
func TestRenoDXMetadataLive(t *testing.T) {
	requireNetwork(t)

	client := &Client{
		HTTP:      &http.Client{Timeout: 60 * time.Second},
		Dir:       t.TempDir(),
		UserAgent: "yarm/test (+https://github.com/secato/yarm)",
		RenoDXURL: RenoDXMetadataURL,
		Now:       time.Now,
	}

	mods, err := client.RenoDX(context.Background())
	if err != nil {
		t.Fatalf("RenoDX(): %v", err)
	}

	// Two hundred-ish today. A collapse to a handful means the format
	// moved and the parser is quietly dropping rows.
	if len(mods) < 100 {
		t.Errorf("parsed %d mods, want at least 100 — the format may have changed", len(mods))
	}

	var withAppID, withArtifact int
	for _, m := range mods {
		if m.SteamAppID != 0 {
			withAppID++
		}
		if len(m.Artifacts) > 0 {
			withArtifact++
		}
	}
	// The Steam app id is what lets the wizard lead with the mod for the
	// game being installed into. Without it the step is just a long list.
	if withAppID < 100 {
		t.Errorf("%d mods carry a Steam app id, want at least 100", withAppID)
	}
	if withArtifact != len(mods) {
		t.Errorf("%d of %d mods have no artifact", len(mods)-withArtifact, len(mods))
	}

	// And the download URL this package builds must actually resolve.
	m := mods[0]
	art, ok := m.ArtifactFor(m.Artifacts[0].Arch)
	if !ok {
		t.Fatalf("ArtifactFor(%s) on %s = !ok", m.Artifacts[0].Arch, m.ID)
	}
	req, err := http.NewRequestWithContext(context.Background(), http.MethodHead, art.URL, nil)
	if err != nil {
		t.Fatal(err)
	}
	resp, err := client.HTTP.Do(req)
	if err != nil {
		t.Fatalf("HEAD %s: %v", art.URL, err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		t.Errorf("HEAD %s = %s, want 200", art.URL, resp.Status)
	}
}
